// <auto-generated />
using Cibus;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cibus.Backend.Migrations
{
    [DbContext(typeof(CibusDatabaseContext))]
    partial class CibusDataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");
#pragma warning restore 612, 618
        }
    }
}
